"""Pass 6: Unparse AST modules to Python source files.

Sig: 2026-04-15 modified
"""
from __future__ import annotations

import ast
import shutil
import subprocess
from pathlib import Path

from restgen.ir.nodes import AppNode
from restgen.codegen.pyproject_emitter import lower_pyproject, lower_requirements


HEADER = "# Generated by restgen -- DO NOT EDIT\n"


def emit(
    modules: dict[str, ast.Module],
    *,
    output_dir: Path,
    format_output: bool = True,
    runtime_src: Path | None = None,
    app: AppNode | None = None,
) -> list[Path]:
    """Write AST modules as Python files to output_dir.

    Steps:
    1. Create output_dir if it does not exist.
    2. Write an empty ``__init__.py``.
    3. For each module, fix locations, unparse to source, prepend header,
       and write to ``output_dir / filename``.
    4. Copy the restgen runtime package into ``output_dir / runtime``.
    5. Optionally format with ruff or black.

    Args:
        modules: Dict from lower pass (filename -> ast.Module).
        output_dir: Target directory for generated files.
        format_output: Whether to format with black/ruff if available.
        runtime_src: Path to restgen runtime package to copy.
            Defaults to the bundled runtime at ``src/restgen/runtime``.

    Returns:
        List of written file paths.

    Sig: 2026-04-14 created
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    # 1. Write __init__.py (from modules dict if present, else empty)
    init_path = output_dir / "__init__.py"
    if "__init__.py" in modules:
        init_module = modules.pop("__init__.py")
        ast.fix_missing_locations(init_module)
        init_source = ast.unparse(init_module)
        init_path.write_text(HEADER + init_source + "\n", encoding="utf-8")
    else:
        init_path.write_text(HEADER, encoding="utf-8")
    written.append(init_path)

    # 2. Write each AST module as a .py file. Nested paths (e.g.
    # ``routers/users.py``) get their parent dirs created and an
    # ``__init__.py`` seeded into each new dir. Every output path is
    # resolved and verified to live under output_dir to block path
    # traversal via malicious import source_paths.
    output_resolved = output_dir.resolve()
    init_dirs_seen: set[Path] = set()

    for filename, module in modules.items():
        ast.fix_missing_locations(module)
        source = ast.unparse(module)
        file_path = (output_dir / filename)
        resolved = file_path.resolve()
        try:
            resolved.relative_to(output_resolved)
        except ValueError:
            raise ValueError(
                f"Refusing to write module {filename!r} outside output_dir "
                f"(resolved to {resolved})"
            )
        file_path.parent.mkdir(parents=True, exist_ok=True)

        # Seed an __init__.py in each new parent dir inside output_dir.
        parent = file_path.parent.resolve()
        while parent != output_resolved and parent not in init_dirs_seen:
            init_file = parent / "__init__.py"
            if not init_file.exists():
                init_file.write_text(HEADER, encoding="utf-8")
                written.append(init_file)
            init_dirs_seen.add(parent)
            if parent.parent == parent:
                break
            parent = parent.parent

        file_path.write_text(HEADER + source + "\n", encoding="utf-8")
        written.append(file_path)

    # 3. Generate pyproject.toml and requirements.txt with auto-detected deps
    if app is not None:
        pyproject_path = output_dir / "pyproject.toml"
        pyproject_path.write_text(lower_pyproject(app), encoding="utf-8")
        written.append(pyproject_path)

        requirements_path = output_dir / "requirements.txt"
        requirements_path.write_text(lower_requirements(app), encoding="utf-8")
        written.append(requirements_path)

    # 4. Copy runtime directory
    if runtime_src is None:
        runtime_src = Path(__file__).resolve().parent.parent / "runtime"

    runtime_dest = output_dir / "runtime"
    if runtime_dest.exists():
        shutil.rmtree(runtime_dest)
    if runtime_src.exists():
        shutil.copytree(runtime_src, runtime_dest)
        # Collect all copied files
        for p in runtime_dest.rglob("*"):
            if p.is_file():
                written.append(p)

    # 5. Format output if requested
    if format_output:
        _try_format(output_dir)

    return written


def _try_format(directory: Path) -> None:
    """Attempt to format generated code with ruff or black.

    Tries ruff first, falls back to black. Silently ignores errors
    if neither formatter is installed.

    Args:
        directory: Directory containing Python files to format.

    Sig: 2026-04-14 created
    """
    # Try ruff first
    try:
        subprocess.run(
            ["ruff", "format", str(directory)],
            capture_output=True,
            timeout=30,
            check=False,
        )
        return
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    # Fall back to black
    try:
        subprocess.run(
            ["black", str(directory)],
            capture_output=True,
            timeout=30,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
