"""Emit a UV-compatible pyproject.toml for the generated project.

Auto-detects dependencies from the AppNode (database type, middleware kinds)
and produces a pyproject.toml with pinned minimum versions.

Sig: 2026-04-15 created
"""
from __future__ import annotations

from restgen.ir.nodes import AppNode


# ---------------------------------------------------------------------------
# Dependency mappings
# ---------------------------------------------------------------------------

_BASE_DEPS: list[str] = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "pydantic>=2.0",
]

_DB_DEPS: dict[str, list[str]] = {
    "memory": [],
    "redis": ["redis>=5.0"],
    "postgres": ["sqlalchemy[asyncio]>=2.0", "asyncpg>=0.29"],
    "sqlite": ["sqlalchemy[asyncio]>=2.0", "aiosqlite>=0.20"],
    "mongo": ["motor>=3.0"],
}

_MIDDLEWARE_DEPS: dict[str, list[str]] = {
    "cors": [],
    "trustedhost": [],
    "gzip": [],
    "rate_limit": ["slowapi>=0.1.9"],
}

_DEV_DEPS: list[str] = [
    "httpx>=0.27",
    "pytest>=8.0",
    "pytest-asyncio>=0.24",
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _collect_deps(app: AppNode) -> list[str]:
    """Collect all runtime dependencies from the IR.

    Inspects ``app.database.db_type`` and ``app.middleware[].kind`` to
    determine which pip packages the generated code needs.

    Args:
        app: The root IR AppNode.

    Returns:
        Ordered list of dependency specifiers.

    Sig: 2026-04-15 created
    """
    deps: list[str] = list(_BASE_DEPS)

    # Database adapter deps
    db_type = ""
    if app.database and app.database.db_type:
        db_type = app.database.db_type.lower()
    for dep in _DB_DEPS.get(db_type, []):
        if dep not in deps:
            deps.append(dep)

    # Middleware deps
    for mw in app.middleware:
        kind = mw.kind.lower()
        for dep in _MIDDLEWARE_DEPS.get(kind, []):
            if dep not in deps:
                deps.append(dep)

    # User-specified extra deps from config
    for dep in app.dependencies:
        if dep not in deps:
            deps.append(dep)

    return deps


def lower_pyproject(app: AppNode) -> str:
    """Generate pyproject.toml content from the IR.

    Args:
        app: The root IR AppNode.

    Returns:
        The full pyproject.toml file content as a string.

    Sig: 2026-04-15 created
    """
    deps = _collect_deps(app)

    # Format project name (slugify title)
    name = app.title.lower().replace(" ", "-").replace("_", "-")
    version = app.version or "0.1.0"

    deps_str = _format_list(deps)
    dev_deps_str = _format_list(_DEV_DEPS)

    return f"""# Generated by restgen -- managed with uv
[project]
name = "{name}"
version = "{version}"
requires-python = ">=3.12"
dependencies = [
{deps_str}]

[tool.uv]
dev-dependencies = [
{dev_deps_str}]
"""


def lower_requirements(app: AppNode) -> str:
    """Generate requirements.txt content from the IR.

    Fallback for environments without UV. Contains the same dependencies
    as the pyproject.toml.

    Args:
        app: The root IR AppNode.

    Returns:
        The requirements.txt file content as a string.

    Sig: 2026-04-15 created
    """
    deps = _collect_deps(app)
    lines = ["# Generated by restgen -- install with: pip install -r requirements.txt"]
    lines.extend(deps)
    lines.append("")  # trailing newline
    return "\n".join(lines)


def _format_list(items: list[str]) -> str:
    """Format a list of strings as indented TOML array entries.

    Sig: 2026-04-15 created
    """
    return "".join(f'    "{item}",\n' for item in items)
